# Generated by Django 6.0.2 on 2026-02-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cover_photo', models.ImageField(blank=True, default='covers/default.jpg', null=True, upload_to='covers/')),
                ('content', models.TextField()),
                ('category', models.CharField(default='uncategorized', max_length=255)),
            ],
        ),
    ]
